name: cs229
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
    - torch
    - transformers
    - sentence-transformers
    - openpyxl
    - jupyter
    - jupyterlab