name: cs229
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1=h7bae524_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - cairo=1.18.4=h6a3b0d2_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - expat=2.7.1=hec049ff_0
  - ffmpeg=8.0.0=gpl_h93d53e2_105
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7af3d76_3
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - giflib=5.2.2=h93a5062_0
  - glslang=15.4.0=h59e7fc5_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py310h8086d47_1
  - graphite2=1.3.14=hec049ff_2
  - harfbuzz=11.4.5=hf4e55d4_0
  - icu=75.1=hfee45f7_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_h0f61937_1
  - kiwisolver=1.4.9=py310h563d721_2
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h88f92a7_1000
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.58.4=h266df6f_3
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.8.0=cpu_generic_he14e14d_2
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - llvmlite=0.45.1=py310h192be34_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib=3.10.7=py310hb6292c7_0
  - matplotlib-base=3.10.7=py310h0181960_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.62.1=py310h68c42a1_0
  - numpy=2.2.6=py310h4d83441_0
  - openfst=1.8.4=ha393de7_1
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - optree=0.17.0=py310h0e897d2_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pango=1.56.4=h875632e_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pillow=12.0.0=py310hab9784f_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h81086ad_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.8.0=cpu_generic_py310_hfc17c52_2
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h0b18652_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=py310hca03da5_0
  - shaderc=2025.3=hafb04c2_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - spirv-tools=2025.4=ha7d2532_0
  - sqlite=3.50.2=h79febb2_1
  - statsmodels=0.14.5=py310hfdc7867_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.8.0=cpu_py310hb61d327_2
  - torchcodec=0.8.1=cpu_py310_h862276c_2
  - torchvision=0.24.0=cpu_py310_ha4b4c0b_2
  - torchvision-extra-decoders=0.0.2=py310hdc67237_4
  - tornado=6.5.2=py310h7bdd564_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.9.post2=py310hbe9552e_0
  - unicodedata2=17.0.0=py310hfe3a0ae_0
  - wheel=0.45.1=py310hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.2.5=h3470cca_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - anyio==4.11.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - msgpack==1.1.2
      - narwhals==2.10.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - plotly==6.4.0
      - pooch==1.8.2
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - redis==7.0.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - send2trash==1.8.3
      - sentence-transformers==5.1.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - spotipy==2.25.1
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - traitlets==5.14.3
      - transformers==4.57.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
prefix: /opt/miniconda3/envs/cs229
